include:
  - compose/storage.yml
  - compose/modeling.yml
  - compose/orchestration.yml
  - compose/observability.yml
  - compose/management.yml
  - compose/quality.yml
  - compose/sso.yml
  - compose/llm.yml
