services:
  _logging:
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

  _micro:
    extends:
      service: _logging
    mem_limit: 96m
    memswap_limit: 96m
    cpus: 0.15
    deploy:
      resources:
        limits:
          memory: 96M
          cpus: "0.15"
        reservations:
          memory: 32M
          cpus: "0.05"

  _small:
    extends:
      service: _logging
    mem_limit: 192m
    memswap_limit: 192m
    cpus: 0.25
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: "0.25"
        reservations:
          memory: 64M
          cpus: "0.05"

  _medium:
    extends:
      service: _logging
    mem_limit: 384m
    memswap_limit: 384m
    cpus: 0.50
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: "0.50"
        reservations:
          memory: 128M
          cpus: "0.10"

  _large:
    extends:
      service: _logging
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 0.75
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.75"
        reservations:
          memory: 192M
          cpus: "0.25"

  _xxlarge:
    extends:
      service: _logging
    mem_limit: 1536m
    memswap_limit: 2304m
    cpus: 2
    deploy:
      resources:
        limits:
          memory: 1536M
          cpus: "2"
        reservations:
          memory: 384M
          cpus: "0.25"
